quarkus.index-dependency.policy-gate.group-id=io.github.braineous-ai-platform
quarkus.index-dependency.policy-gate.artifact-id=dd-module-policygate

quarkus.index-dependency.llmdd-query-client.group-id=io.github.braineous-ai-platform
quarkus.index-dependency.llmdd-query-client.artifact-id=llmdd-query-client